In [ ]:
import numpy as np        #importing moduls
import matplotlib.pyplot as plt
import os
import cv2
import pandas as pd

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit
import cv2
# import albumentations as albu
from skimage.transform import resize
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from pylab import rcParams
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from keras.callbacks import Callback, EarlyStopping, ReduceLROnPlateau
import tensorflow as tf
import keras
from keras.models import Sequential, load_model
from keras.layers import Dropout, Dense, GlobalAveragePooling2D
from keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ModelCheckpoint


In [ ]:
img_size = 224

In [ ]:
path = 'D:/train_data/train/train' 
# output_path_folder = ''

path_index="D:/train_data/trainLabels.csv"
count=0
images_arrays=[]
resized_images=[]



data=pd.read_csv(path_index)   #reducing data 

data_0=data[data['level']==0]
data_0=data_0.head(1000)

data_1=data[data['level']==1]
data_1=data_1.head(1000)

data_2=data[data['level']==2]
data_2=data_2.head(1100)

data_3=data[data['level']==3]
data_4=data[data['level']==4]

labels_used=pd.concat([data_0,data_1,data_2,data_0,data_1,data_2,data_3,data_4,data_3,data_4])
labels_used=labels_used.sample(frac=1,random_state=42)   #shuffling data
actual_labels=labels_used['level']
labels_used=labels_used['image']
actual_labels=np.array(actual_labels)

In [ ]:
y_train_true=[]  #1-hot encoding
for i in actual_labels:
    l=np.zeros(5)
    l[i]=1
    y_train_true.append(l)
y_train_true=np.array(y_train_true)

In [ ]:
# resized_images=[]

In [ ]:

# image preprocessing

count = 0
for img in labels_used:
    img=img+'.jpeg'
    bgr_img = cv2.imread(os.path.join(path,img))
    # bgr_img = cv2.resize(bgr_img, (img_size,img_size))
    image_bw = cv2.cvtColor(bgr_img, cv2.COLOR_BGR2GRAY)  #making images black and white
    # hsv_img = cv2.cvtColor(bgr_img, cv2.COLOR_BGR2HSV)
    rbg_img = cv2.cvtColor(bgr_img, cv2.COLOR_BGR2RGB)

    # gray_three = cv2.merge([image_bw,image_bw,image_bw])
    # hsv_img = cv2.cvtColor(rbg_img, cv2.COLOR_BGR2HSV)

    clahe = cv2.createCLAHE(clipLimit = 5)  #increasing contrast
    final_img = clahe.apply(image_bw)

    # plt.imshow(final_img)
    # plt.show()
    
    #finding ends for croping
    img_processed = (np.array(final_img)-6)/255  #removing a reductant purple layer
    variance=1
    col_sum = np.sum(img_processed, axis=0)  #Cropping of free space
    row_sum = np.sum(img_processed, axis=1)
    coordx = []
    coordy = []
    for i,j in enumerate(col_sum):
        if j>variance:
            coordx.append(i)
    for i,j in enumerate(row_sum):
        if j>variance:
            coordy.append(i)

    final_img = final_img[coordy[0]:coordy[-1]:, coordx[0]:coordx[-1]]
    
    gray_three = cv2.merge([final_img,final_img,final_img])
    gray_three = cv2.resize(gray_three, (img_size,img_size))
    resized_images.append(gray_three)
    count+=1
    if (count%100==0):
        print(count)


100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000


KeyboardInterrupt: 

In [ ]:
# resized_images2=np.array(resized_images)
# np.save('x_train',resized_images2)

In [ ]:

x_train = np.load('x_train.npy')
x_train = np.array(x_train, np.float32) 


In [ ]:
from keras.models import Sequential 
from tensorflow.keras.applications import ResNet50

In [ ]:
# np.save('y_train.npy',y_train_true)

In [ ]:
from sklearn.model_selection import train_test_split
x_train2,x_valid,y_train,y_valid=train_test_split(x_train,y_train_true,test_size=0.2)

In [ ]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.applications import VGG19

In [ ]:
# model=Sequential()   #Building a sequential model and implimenting transfer learning
# model_efficient=ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3),classes=5)
# for layers in model_efficient.layers:
#     layers.trainable=False

# model.add(model_efficient)
# model.add(MaxPool2D((2,2),padding='same'))
# model.add(GlobalAveragePooling2D())
# model.add(Dropout(0.3))
# model.add(Dense(256, activation='relu'))

# model.add(Dense(5, activation='softmax'))
# model.summary()

In [ ]:
# model=Sequential()
# model_efficient=EfficientNetB7(weights='imagenet',include_top=False,input_shape=(260,260,3),classes=5)
# for layers in model_efficient.layers:
#     layers.trainable=False


# model.add(model_efficient)
# model.add(GlobalAveragePooling2D())
# model.add(Dropout(0.3))
# model.add(Dense(256, activation='relu'))

# model.add(Dense(5, activation='softmax'))
# model.summary()
import tensorflow as tf
model=tf.keras.models.load_model('accuracy_72p.model')

In [ ]:
# es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=100)
# mc=ModelCheckpoint('best_after74.h5',monitor='val_accuracy',mode='max',verbose=1,save_best_only=True)
# model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

# model.fit(x_train2,y_train,validation_data=(x_valid,y_valid),verbose=1,callbacks=[es,mc],epochs=10,batch_size=50)


Epoch 1/10
150/150 [==============================] - ETA: 0s - loss: 0.5702 - accuracy: 0.7737
Epoch 1: val_accuracy improved from -inf to 0.70475, saving model to best_after74.h5
150/150 [==============================] - 428s 3s/step - loss: 0.5702 - accuracy: 0.7737 - val_loss: 0.7565 - val_accuracy: 0.7048
Epoch 2/10
150/150 [==============================] - ETA: 0s - loss: 0.5606 - accuracy: 0.7797
Epoch 2: val_accuracy improved from 0.70475 to 0.73572, saving model to best_after74.h5
150/150 [==============================] - 592s 4s/step - loss: 0.5606 - accuracy: 0.7797 - val_loss: 0.6906 - val_accuracy: 0.7357
Epoch 3/10
150/150 [==============================] - ETA: 0s - loss: 0.5671 - accuracy: 0.7729
Epoch 3: val_accuracy did not improve from 0.73572
150/150 [==============================] - 645s 4s/step - loss: 0.5671 - accuracy: 0.7729 - val_loss: 0.7101 - val_accuracy: 0.7229
Epoch 4/10
150/150 [==============================] - ETA: 0s - loss: 0.5542 - accuracy: 0.7

In [ ]:
y_pred=model.predict(x_valid)

59/59 [==============================] - 70s 1s/step


In [ ]:
y_pred_net=[]
for i in y_pred:
    y_pred_net.append(np.argmax(i))
y_pred_net=np.array(y_pred_net)

In [ ]:
y_pred_t=[]
for i in y_valid:
    y_pred_t.append(np.argmax(i))
y_pred_t=np.array(y_pred_t)

In [ ]:
y_pred_t

array([2, 2, 4, ..., 1, 2, 2], dtype=int64)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred_t,y_pred_net))
confusion_matrix(y_pred_t,y_pred_net)

0.7271756540309664


array([[229, 111,  29,  13,   5],
       [ 44, 327,  16,  12,   0],
       [ 59, 116, 223,  34,  10],
       [ 10,  16,  15, 318,   3],
       [  0,   6,   7,   5, 265]], dtype=int64)

In [ ]:
y_valid

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
# model.save('accuracy_72p.model')

INFO:tensorflow:Assets written to: accuracy_72p.model\assets


INFO:tensorflow:Assets written to: accuracy_72p.model\assets
